### PR TITLE
feat: exclude files from frontmatter

### PR DESCRIPTION
**Pull request by aslafy-z**
Decide if a file is excluded from sidebar in that file front matter definition.

### CODE REVIEW

**Comment by jooy2** [comment]
Hello. Thank you for your contribution to the project.

Can you tell me the current status of this PR? If you're done with it, please remove the draft status and i'll merge it after review.

Regards,

**Comment by maxwowpow** [comment]
I like the feature! :) @aslafy-z

**Comment by aslafy-z** [comment]
Hello @jooy2 
This PR is now ready for review. Let me know !
Regards,

**Comment by jooy2** [comment]
Hello! Thank you for your patience.

I've reviewed your code and found nothing out of the ordinary and it passes tests, so i'll merge this code.

Thanks for the great work!

Regards,

**Review by jooy2 — APPROVED** [review]

**Pull request merged**
